### PR TITLE
small updates

### PR DESCRIPTION
**Pull request by excalibur1234**

### CODE REVIEW

**Comment by Chrysostomus** [comment]
This is good idea and problem it solves is real. I'm not sure if it is the best solution though. I did the same by putting `sleep 30 && update-checker` in my autostart, but if delay is hardcoded, makes the script less flexible.

How about we start by checking connection with ping every 30s until there is connection, and start the while loop only then? I think that it might be both more flexible and less error prone than hardcoded 30s delay.

What do you think?

**Comment by Chrysostomus** [comment]
This would do it once...

```
#! /bin/bash
## Check for updates on regular intervals
checker()
{
while true; do
    update-notifier
    sleep $1
done
}

delayed_checker()
{
    sleep 45 && checker
}

main()
{
    ping -c 1 8.8.8.8 >/dev/null 2>&1 && checker || delayed_checker
}

main
```

But I haven't yet figured how to check until successful...

**Comment by Chrysostomus** [comment]
Found it. What do you think about this one?

```

#! /bin/sh
interval=${1:-7200}

connection()
{
    ping -c 1 8.8.8.8 >/dev/null 2>&1
}
waiter()
{
if ! connection ; then
    sleep 10 && waiter
else
    checker
fi
}
checker()
{
while true; do
    update-notifier
    sleep "$interval"
done
}
waiter
```

It checks for net connection every 10 seconds, and when it has connection it stops and runs the same update loop as previously. Default is every two hours, but arguments are accepted as before. I think this might be good.

**Comment by excalibur1234** [comment]
this looks good.
but i would increase the default to 4 or 6 hours.

i see you have already implemented it. can you still implement my changes to the readme file?

**Comment by Chrysostomus** [comment]
Okay, I'll implement them and increase the default.

**Pull request closed without merging**
